services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"   # REST API
      - "50051:50051" # gRPC
    environment:
      - MONGODB_URI=mongodb://user-service-mongo:27017
      - DB_NAME=user_service
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_EXPIRY=24h
      - PORT=8080
      - GRPC_PORT=50051
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - user-service-network

  mongo:
    image: mongo:latest
    container_name: user-service-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - user-service-network

volumes:
  mongo-data:

networks:
  user-service-network:
    driver: bridge